### PR TITLE
Update docker-maven-plugin version to latest [ARCH-68] [ARCH-69]

### PR DESCRIPTION
**Pull request by mattbetzel**
Also change Docker activation to using docker.ip build property.

### CODE REVIEW

**Comment by mattbetzel** [comment]
@matt-haigh and @skingsland can I get a review?  I'm going push this change through _pose-parent_ to _bertha_.

**Comment by matt-haigh** [comment]
LGTM :+1:

Heads up that pose-parent is currently on opower-parent 2.2.0.  When you bump it to 2.5.0, you're going to pick up an upgrade to the checkstyle plugin (2.11 to 2.15).  This will probably cause some whitespace checkstyle errors in bertha when you bump it's pose-parent version.  Here's a link to a commit I made in core preparing it for the checkstyle upgrade: https://github.va.opower.it/eng-main/core/commit/2e6698febfb006f33ab378f29f19f7633a8cf95b

**Comment by akanter** [comment]
Looks fine-ish, but won't the difference between `docker.ip` and `docker.host` break a bunch of folks?

Also as far as checkstyle goes, as long as we stick to the 1.17 rules, we should probably be OK with whitespace. One thing we'll probably need to do is add the appropriate dependency on the version of the puppycrawl checkstyle tool since maven-checkstyle-plugin v2.15 uses puppycrawl checkstyle v6.1.1 by default (maven-checkstyle-plugin v2.11 used checkstyle 5.6, so we may want to start with that). If you have questions about any of this, obviously feel free to ping me.

**Comment by matt-haigh** [comment]
@akanter The left curly whitespace errors I fixed in core when upgrading checkstyle plugin from 2.11 to 2.15 were more specifically due to a bug in left curly checking that was fixed in puppycrawl checkstyle rules v5.8.  So you're totally right - if we peg the puppycrawl checkstyle version at 5.6 in pose-parent, we can pull in the updated version of opower-parent and not have to fix the left curly errors right away.

**Comment by mattbetzel** [comment]
@akanter I can count on one hand the people that possibly could be affected by this.  I'll make sure they make the necessary changes to _~/.m2/settings.xml_.  The documentation for Archmage has already been updated.

**Comment by mattbetzel** [comment]
I've also push this change all the way down to Bertha locally without breaking any of the artifacts.  Do you want me to modify any checkstyle configuration in addition to updating to latest _opower-parent_?

**Comment by akanter** [comment]
@mattbetzel We can talk more about the pose-parent changes on the pose-parent pr, but yeah we probably ought to test out locking the puppycrawl checkstyle version to 5.6 in pose-parent for the time being. These changes look fine though. Are you OK to self merge?

**Pull request merged**
