### PR TITLE
Re 3672 make master the release branch again

### PR DESCRIPTION
**Pull request by jamlevi**
we deviated from our release from master model to upgrade to cdh5. This commit will bring us back inline with our original model. I will release 4.0.0 from master post-merge and update pose-parent to 4.0.0.

### CODE REVIEW

**Comment by jamlevi** [comment]
I guess I should have squashed this ?

**Comment by mattbetzel** [comment]
@jamlevi can you hold off on the 4.0.0 release until I get a small PR in related to Docker?

**Comment by jamlevi** [comment]
@mattbetzel sure.

**Comment by jamlevi** [comment]
Going to close this one, as we don't want 17 commits. Will redo.

**Pull request closed without merging**
