### PR TITLE
NO-REF Updates maven-checkstyle-plugin to 2.15

### PR DESCRIPTION
**Pull request by akanter**
To support some newer checkstyle features.

### CODE REVIEW

**Comment by kassiel2** [comment]
update release notes

**Comment by akanter** [comment]
@kassiel2 Done.

**Comment by tvaughan77** [comment]
@akanter check the Opower wiki for the release instructions; there's an extra flag you need and a key to install...  IM me if you have problems.

**Comment by amir20** [comment]
What are the new features that we need?

**Comment by akanter** [comment]
@amir20 Support for some additional flags on the WhitespaceAround module. Specifically the "AllowEmptyTypes" flag was unrecognized.

**Pull request merged**
